export const trans = ({
    username: 'שם משתמש',
    password: 'סיסמא',
    usernameError: 'חובה להזין שם משתמש',
    passwordError: 'חובה להזין סיסמא',
    connect: 'התחבר',
    earth: 'התרשמות אישית',
    saturn: 'חשיבה דיגיטלית',
    venus: 'עיצוב',
    mars: 'עד כמה המוצר מתאים לדרישות של הבנק',
    hello: 'שלום {{fullName}}',
    systemConnection: 'כניסה למערכת הדירוגים',
    chooseProject: 'אנא בחר פרוייקט מתוך רשימת הפרוייקטים אשר מטה ודרג כל פרוייקט בנפרד, אנא הקפד לדרג את כל הפרוייקטים ברשימה',
    rate: 'שלח דירוג',
    errorHapened: 'אירעה שגיאה, אנא פנה לאחראי',
    projectRegistred: 'תודה על הדירג של היוזמה: {{projectName}}, הדירוג שלך נרשם בהצלחה',
    chooseRating: 'אנא בחר דירוג',
    summaryTable: 'טבלת סיכום',
    projectName: 'שם הפרוייקט',
    summaryNumber: 'ציון מסכם',
    judgesList: 'שופטים',
    judgesSubList: 'בחר שופט ולחץ על הכפתור על מנת לראות את הדירוד שלו',
    judgeError: 'חובה לבחור שופט',
    judge: 'שופט',
    watchJudge: 'צפה בדירוגים של השופא'
});
